[package]
name = "cos-cli"
version = "0.2.0"
edition = "2024"

[dependencies]
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
cosmic-protocols = { git = "https://github.com/pop-os/cosmic-protocols", features = ["client"] }
pico-args = "0.5"
